document.getElementById("pdfBtn").addEventListener("click", async () => {
    const status = document.getElementById("status");
    status.textContent = "Generating PDF...";
    
    try {
      // Get the currently active tab
      let [tab] = await browser.tabs.query({ active: true, currentWindow: true });
      
      // Call Firefox's built-in, exclusive 'saveAsPDF' method
      // This is unique to Mozilla Firefox!
      await browser.tabs.saveAsPDF({
        headerLeft: tab.title,
        headerRight: tab.url,
        footerCenter: "Generated by PDF Converter",
        footerRight: "&PT" // Adds the Page Number
      });
      
      status.style.color = "#059669"; // Green
      status.textContent = "PDF Saved to Downloads!";
      
    } catch (err) {
      console.error(err);
      
      // Fallback: If it's a restricted page, trigger the print dialog
      status.style.color = "#d97706"; // Yellow
      status.textContent = "Opening Print Dialog...";
      
      let [tab] = await browser.tabs.query({ active: true, currentWindow: true });
      browser.scripting.executeScript({
          target: { tabId: tab.id },
          func: () => { window.print(); }
      });
    }
});
